### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by yym68686** [Lin-jun-xiang/action-translate-readme#5]
GitHub Action logs:

```
Notice:  A new release of pip is available: 23.0.1 -> 23.2.1
Notice:  To update, run: pip install --upgrade pip
Collecting tenacity
  Obtaining dependency information for tenacity from https://files.pythonhosted.org/packages/f4/f1/990741d5bb2487d529d20a433210ffa136a367751e454214013b441c4575/tenacity-8.2.3-py3-none-any.whl.metadata
  Downloading tenacity-8.2.3-py3-none-any.whl.metadata (1.0 kB)
Downloading tenacity-8.2.3-py3-none-any.whl (24 kB)
Installing collected packages: tenacity
Successfully installed tenacity-8.2.3

Notice:  A new release of pip is available: 23.0.1 -> 23.2.1
Notice:  To update, run: pip install --upgrade pip
Run export PROVIDER=g4f.Provider.DeepAi
README.md changed.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/g4f/Provider/helper.py", line 21, in get_event_loop
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/runner/work/_actions/Lin-jun-xiang/action-translate-readme/v2/translation.py", line 34, in chat_completion
    return g4f.ChatCompletion.create(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/g4f/__init__.py", line 55, in create
    return result if stream else ''.join(result)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/g4f/Provider/base_provider.py", line 99, in create_completion
    loop = get_event_loop()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/g4f/Provider/helper.py", line 23, in get_event_loop
    return _event_loop_policy.get_event_loop()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (worker)'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/_actions/Lin-jun-xiang/action-translate-readme/v2/translation.py", line 115, in <module>
    main()
  File "/home/runner/work/_actions/Lin-jun-xiang/action-translate-readme/v2/translation.py", line 111, in main
    pool.map(multi_exec, LAGNS)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/runner/work/_actions/Lin-jun-xiang/action-translate-readme/v2/translation.py", line 102, in multi_exec
    translated_content = translate_content(content, output_lang)
  File "/home/runner/work/_actions/Lin-jun-xiang/action-translate-readme/v2/translation.py", line 53, in translate_content
    response = chat_completion(translate_query)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/__init__.py", line [289](https://github.com/yym68686/ChatGPT-Telegram-Bot/actions/runs/6314161905/job/17143809226#step:3:302), in wrapped_f
    return self(f, *args, **kw)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fbbf7e9e230 state=finished raised RuntimeError>]
Error: Process completed with exit code 1.
```

**Comment by Lin-jun-xiang** [comment]
@yym68686 
This error should be coming from `gpt4free`, and in fact, I've encountered it a few times before. However, sometimes it suddenly starts working again.

Therefore, I suggest you create a `test` branch and make changes to the README in that `test` branch, then trigger the Actions.

see: gpt4free[#915](https://github.com/xtekky/gpt4free/issues/915)

**Comment by Lin-jun-xiang** [comment]
@yym68686 
Thank you for your feedback. I believe the issue is caused by a conflict between `asyncio` in `g4f` and the use of `multiThread` in `translate.py`, even though this issue did not occur before.

**Comment by Lin-jun-xiang** [comment]
@yym68686 

This problem should be solved. Use `asyncio` instead of `multithread` to call `g4f`.

Please check again. If there have any problem, just tag me!

**Comment by yym68686** [comment]
It's already usable, very user-friendly, thank you! 🎉
